#pragma once
#include "pressabledefs.h"

namespace fin::input {
  enum class Keycode {
    UNDEFINED,

    MENU,

    ACCENT,

    PRINTSCREEN,

    PAUSE,

    HOME, END,
    WORLD_1, WORLD_2,

    COMMA, MINUS, PERIOD, APOSTROPHE,
    LOCK_CAPS, LOCK_SCROLL, LOCK_NUM,
    SLASH_FORWARD, SLASH_BACKWARD,
    BRACKET_LEFT, BRACKET_RIGHT, PARENTHESES_LEFT, PARENTHESES_RIGHT,
    PAGEUP, PAGEDOWN,
    LEFT, RIGHT, UP, DOWN,
    TAB, SPACEBAR, ENTER, ESC, INSERT, DEL, BACKSPACE, EQUAL, SEMICOLON,
    SHIFT_LEFT, ALT_LEFT, CTRL_LEFT, SYSTEM_LEFT,
    SHIFT_RIGHT, ALT_RIGHT, CTRL_RIGHT, SYSTEM_RIGHT,

    NUMPAD_0, NUMPAD_1, NUMPAD_2, NUMPAD_3, NUMPAD_4, NUMPAD_5, NUMPAD_6,
    NUMPAD_7, NUMPAD_8, NUMPAD_9,
    NUMPAD_DIVIDE, NUMPAD_MULTIPLY, NUMPAD_SUBTRACT, NUMPAD_ADD, NUMPAD_ENTER,
    NUMPAD_EQUAL, NUMPAD_DECIMAL,

    NUM_0, NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, NUM_7, NUM_8, NUM_9,
    A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y,
    Z,
    F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17,
    F18, F19, F20, F21, F22, F23, F24, F25
  };
}
