#pragma once

enum Keycode {
  KEYCODE_UNDEFINED,

  KEYCODE_MENU,

  KEYCODE_ACCENT,

  KEYCODE_PRINTSCREEN,

  KEYCODE_PAUSE,

  KEYCODE_HOME, KEYCODE_END,
  KEYCODE_WORLD_1, KEYCODE_WORLD_2,

  KEYCODE_COMMA, KEYCODE_MINUS, KEYCODE_PERIOD, KEYCODE_APOSTROPHE,
  KEYCODE_LOCK_CAPS, KEYCODE_LOCK_SCROLL, KEYCODE_LOCK_NUM,
  KEYCODE_SLASH_FORWARD, KEYCODE_SLASH_BACKWARD,
  KEYCODE_BRACKET_LEFT, KEYCODE_BRACKET_RIGHT, KEYCODE_PARENTHESES_LEFT, KEYCODE_PARENTHESES_RIGHT,
  KEYCODE_PAGEUP, KEYCODE_PAGEDOWN,
  KEYCODE_LEFT, KEYCODE_RIGHT, KEYCODE_UP, KEYCODE_DOWN,
  KEYCODE_TAB, KEYCODE_SPACEBAR, KEYCODE_ENTER, KEYCODE_ESC, KEYCODE_INSERT, KEYCODE_DELETE, KEYCODE_BACKSPACE, KEYCODE_EQUAL, KEYCODE_SEMICOLON,
  KEYCODE_SHIFT_LEFT, KEYCODE_ALT_LEFT, KEYCODE_CTRL_LEFT, KEYCODE_SYSTEM_LEFT,
  KEYCODE_SHIFT_RIGHT, KEYCODE_ALT_RIGHT, KEYCODE_CTRL_RIGHT, KEYCODE_SYSTEM_RIGHT,

  KEYCODE_NUMPAD_0, KEYCODE_NUMPAD_1, KEYCODE_NUMPAD_2, KEYCODE_NUMPAD_3, KEYCODE_NUMPAD_4, KEYCODE_NUMPAD_5, KEYCODE_NUMPAD_6, KEYCODE_NUMPAD_7, KEYCODE_NUMPAD_8, KEYCODE_NUMPAD_9,
  KEYCODE_NUMPAD_DIVIDE, KEYCODE_NUMPAD_MULTIPLY, KEYCODE_NUMPAD_SUBTRACT, KEYCODE_NUMPAD_ADD, KEYCODE_NUMPAD_ENTER, KEYCODE_NUMPAD_EQUAL, KEYCODE_NUMPAD_DECIMAL,

  KEYCODE_0, KEYCODE_1, KEYCODE_2, KEYCODE_3, KEYCODE_4, KEYCODE_5, KEYCODE_6, KEYCODE_7, KEYCODE_8, KEYCODE_9,
  KEYCODE_A, KEYCODE_B, KEYCODE_C, KEYCODE_D, KEYCODE_E, KEYCODE_F, KEYCODE_G, KEYCODE_H, KEYCODE_I, KEYCODE_J, KEYCODE_K, KEYCODE_L, KEYCODE_M, KEYCODE_N, KEYCODE_O, KEYCODE_P, KEYCODE_Q, KEYCODE_R, KEYCODE_S, KEYCODE_T, KEYCODE_U, KEYCODE_V, KEYCODE_W, KEYCODE_X, KEYCODE_Y, KEYCODE_Z,
  KEYCODE_F1, KEYCODE_F2, KEYCODE_F3, KEYCODE_F4, KEYCODE_F5, KEYCODE_F6, KEYCODE_F7, KEYCODE_F8, KEYCODE_F9, KEYCODE_F10, KEYCODE_F11, KEYCODE_F12, KEYCODE_F13, KEYCODE_F14, KEYCODE_F15, KEYCODE_F16, KEYCODE_F17, KEYCODE_F18, KEYCODE_F19, KEYCODE_F20, KEYCODE_F21, KEYCODE_F22, KEYCODE_F23, KEYCODE_F24, KEYCODE_F25
};

